name: Main Pipeline
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-push:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # https://github.com/aws-actions/amazon-ecr-login/issues/587

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Dump all outputs from login-ecr step
        run: echo "Registry: ${{ steps.login-ecr-public.outputs.registry }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build using github cache
        uses: docker/build-push-action@v3
        with:
          load: true
          push: false
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:latest-main
          cache-to: type=gha,mode=max
          cache-from: type=gha

      - name: Push the image to Amazon ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:latest-main
